name: Release Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: dadyarri-ntp-v${{ github.ref }}
          path: dist

      - name: Get Release ID
        id: get_release_id
        run: echo ::set-output name=release_id::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref }} | jq '.id')

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dadyarri-ntp-v${{ github.ref }}

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release_id.outputs.release_id }}/assets?name=dadyarri-ntp-v${{ github.ref }}.zip
          asset_path: dadyarri-ntp-v${{ github.ref }}.zip
          asset_name: dadyarri-ntp-v${{ github.ref }}.zip
          asset_content_type: application/zip