name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Archive Build
        run: zip dadyarri-ntp-v${{ github.ref_name }}.zip -r dist/*

      - name: Get Release ID
        id: get_release_id
        run: echo "release_id=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq '.id')" >> $GITHUB_OUTPUT

      - name: Test
        run: |
          pwd
          ls
          ls assets

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release_id.outputs.release_id }}/assets?name=dadyarri-ntp-v${{ github.ref_name }}.zip
          asset_path: dadyarri-ntp-v${{ github.ref_name }}.zip
          asset_name: dadyarri-ntp-v${{ github.ref_name }}.zip
          asset_content_type: application/zip